// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site-read.sql

package db

import (
	"context"
)

const getPlants = `-- name: GetPlants :many
SELECT
    id, name, is_on
FROM
    site
ORDER BY
    name
`

func (q *Queries) GetPlants(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, getPlants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(&i.ID, &i.Name, &i.IsOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
