// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	Key         string
	Description pgtype.Text
	IsGlobal    pgtype.Bool
}

type Site struct {
	ID   pgtype.UUID
	Name string
	IsOn bool
}

type SitesPermissionGroup struct {
	ID         pgtype.UUID
	SiteID     pgtype.UUID
	Name       string
	Permission string
}

type SitesUser struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	SiteID pgtype.UUID
}

type User struct {
	ID         pgtype.UUID
	ExternalID string
}
