// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.inserts.sql

package db

import (
	"context"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (
    name, is_on
) values (
    $1, false
)
RETURNING id, name, is_on
`

func (q *Queries) CreateSite(ctx context.Context, name string) (Site, error) {
	row := q.db.QueryRow(ctx, createSite, name)
	var i Site
	err := row.Scan(&i.ID, &i.Name, &i.IsOn)
	return i, err
}
