// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit-write.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEntry = `-- name: CreateAuditEntry :exec
INSERT INTO
    audit_log (
        actor_id,
        actor_name,
        action,
        target_type,
        target_id,
        trace_id,
        metadata
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuditEntryParams struct {
	ActorID    string
	ActorName  string
	Action     string
	TargetType string
	TargetID   pgtype.UUID
	TraceID    pgtype.Text
	Metadata   []byte
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error {
	_, err := q.db.Exec(ctx, createAuditEntry,
		arg.ActorID,
		arg.ActorName,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TraceID,
		arg.Metadata,
	)
	return err
}
