// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit-read.sql

package db

import (
	"context"
)

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT
    id,
    occurred_at,
    actor_id,
    actor_name,
    action,
    target_type,
    target_id,
    trace_id,
    metadata
FROM
    audit_log
ORDER BY
    occurred_at DESC,
    id DESC
LIMIT
    $1
`

func (q *Queries) ListAuditEntries(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.TraceID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
