// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site-write.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const setSiteIsOn = `-- name: SetSiteIsOn :one
UPDATE site
SET
    is_on = $2
WHERE
    id = $1
RETURNING
    id, name, is_on
`

type SetSiteIsOnParams struct {
	ID   pgtype.UUID
	IsOn bool
}

func (q *Queries) SetSiteIsOn(ctx context.Context, arg SetSiteIsOnParams) (Site, error) {
	row := q.db.QueryRow(ctx, setSiteIsOn, arg.ID, arg.IsOn)
	var i Site
	err := row.Scan(&i.ID, &i.Name, &i.IsOn)
	return i, err
}
